parameters:
    database_driver: pdo_sqlite
    database_host: localhost
    database_port: null
    database_name: WichList
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 0962429e7436d475907e2ebfcc9bc07d256dc347
    database_path: null
